extends:
  - standard
  - plugin:react/recommended
rules:
  indent:
    - error
    - 4
  react/no-find-dom-node: 0
plugins:
  - react
globals:
  global: true
  describe: true
  it: true
  beforeEach: true
